fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /panel/profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /panel/profile

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    prefix: /admin
    type: annotation

front:
    resource: "@AppBundle/Controller/FrontController.php"
    prefix: /
    type: annotation

map:
    resource: "@AppBundle/Controller/MapController.php"
    prefix: /panel
    type: annotation

post:
    resource: "@AppBundle/Controller/PostController.php"
    prefix: /panel
    type: annotation

