fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /panel/profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /panel/profile

app:
    resource: '@AppBundle/Controller/'
    type: annotation
